spring:
  datasource:
    url: jdbc:mysql://47.94.215.148:3306/my_second_kill?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  kafka:
    bootstrap-servers: 47.94.215.148:9092
    consumer:
      group-id: seconds-kill
    template:
      default-topic: SECONDS-KILL-TOPIC
    listener:
       concurrency: 3

jedisPoolConfig:
  host: 47.94.215.148
  port: 6379
  password: 123456
  maxTotal: 300
  maxIdle: 100
  maxWait: 10000
  testOnBorrow: true
  blockWhenExhausted: true
  timeout: 2000




